#
#server:
#  port: 9090

spring:
  
  datasource:
    url: jdbc:mysql://localhost:3306/allocationDB?createDatabaseIfNotExist=true
    password: en
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none



security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8191/oauth/check_token
    client:
      client-id: web
      client-secret: web